# Jordi Blasco Lozano
# ***Informe sobre Fundamentos de Numpy***

## **1. Introducción**
 En este informe, exploraremos los fundamentos de NumPy, una biblioteca fundamental para la computación numérica en Python. NumPy proporciona estructuras  de datos y operaciones eficientes para manejar matrices y matrices multidimensionales.

## **2. Creación de matrices**

 Las matrices de NumPy son más eficientes que las listas de Python, especialmente para conjuntos de datos grandes, ya que se almacenan en bloques de memoria contiguos. Las matrices pueden crearse a partir de listas o con números aleatorios utilizando las funciones de NumPy.

 Ejemplo de código:

In [1]:
import numpy as np

# Crear un array con los números del 0 al 9
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

# Crear un array de 2 dimensiones
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(b)

# Crear un array de 5 x 6 con números aleatorios
c = np.random.rand(5, 6)
print(c)

# Crear un array de 4 x 4 con numeros enteros aleatorios entre el 0 y el 1
d = np.random.randint(0,2, size=(4,4))
print(d)

# Crear un array aleatoria de mas de dos dimensiones
e = np.random.rand(1, 4, 5)
print(e)

# Mostrar las dimensiones de un array
f = e.shape
print(f)

[0 1 2 3 4 5 6 7 8 9]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[0.0966126  0.99244799 0.11363061 0.3909211  0.53277036 0.78736826]
 [0.69789108 0.19352242 0.05997261 0.8286652  0.65121857 0.63323113]
 [0.86719573 0.55556508 0.11211107 0.63454774 0.63548764 0.15303089]
 [0.18881639 0.0858743  0.03254274 0.35499626 0.01733259 0.62458901]
 [0.28585574 0.13616081 0.04890862 0.2813263  0.05556488 0.37881576]]
[[1 0 0 0]
 [1 0 1 1]
 [0 0 0 0]
 [1 0 1 0]]
[[[0.31540705 0.25908333 0.72119754 0.40361253 0.15260506]
  [0.88038924 0.36668577 0.56207804 0.89148642 0.2998258 ]
  [0.57047978 0.76840068 0.60484721 0.79557512 0.4884022 ]
  [0.16550412 0.57805729 0.92247959 0.11415063 0.50604835]]]
(1, 4, 5)


## **3. Acceso a elementos**
Los elementos en las matrices de NumPy pueden accederse mediante indexación y segmentación, muy similar a las listas de Python. Los índices negativos son compatibles para acceder a elementos y subconjuntos de matrices.

Ejemplo de código:

In [2]:
import numpy as np

# Crear un array de 2 dimensiones
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(a[0, 0])  # Acceder al primer elemento
print(a[-1, -1])  # Acceder al último elemento
print(a[0, :])  # Acceder a la primera fila
print(a[:, 0])  # Acceder a la primera columna

0
8
[0 1 2]
[0 3 6]


## **4. Operaciones**
 NumPy proporciona varias operaciones para manipular matrices, incluyendo operaciones elemento a elemento, multiplicación de matrices, transmisión, comparación, operaciones lógicas, y más.

### **4.1. Operaciones con la misma array**


 Ejemplo de código:

In [2]:
import numpy as np

# Crear un array
A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(str(A + 1) + '\n')  # Sumar 1 a cada elemento
print(str(A * 2)+ '\n')  # Multiplicar cada elemento por 2
print(str(A.sum())+ '\n')  # Calcular la suma de todos los elementos
print(str(A.mean())+ '\n')  # Calcular la media de todos los elementos
print(str(A ** 2)+ '\n')  # Elevar a 2 cada elemento
print(str(A.sum(axis=1))+ '\n')  # Calcular la suma de cada fila por separado
print(str(A.mean(axis=0))+ '\n')  # Calcular la media de cada columna por separado
print(str(A[0, :] < 1) + '\n')  # Calcular si los elementos de la primera fila son menores a 1

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

36

4.0

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

[ 3 12 21]

[3. 4. 5.]

[ True False False]


### **4.2 Operaciones con distintas arrays**

Ejemplo de código:

In [ ]:
import numpy as np

# Crear un array
A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
B = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

print(str(A + B)+'\n')  # Suma de arrays
print(str(A @ B))  # Multiplicacion de arrays

[[0 2 2]
 [4 4 6]
 [6 8 8]]
[[ 1  2  1]
 [ 4  8  4]
 [ 7 14  7]]


### **4.3 Manipulación de la forma**
Las operaciones de manipulación de la forma como aplanamiento, transposición y remodelación permiten un manejo flexible de las dimensiones de la matriz.

Ejemplo de código:


In [ ]:
import numpy as np

# Crear un array
A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(A.flatten())  # Aplanar el array
print(A.T)  # Transponer el array
print(A.reshape(9, 1))  # Remodelar el array

[0 1 2 3 4 5 6 7 8]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### **4.4 Eigenvalores y eigenvectores**
NumPy permite el cálculo de los eigenvalores y eigenvectores de matrices, esenciales para diversas aplicaciones matemáticas y científicas.

Ejemplo de código:

In [ ]:
import numpy as np

# Crear un array de 2 dimensiones
a = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[1.36846584e+01 1.31534156e+00 1.06234298e-17]
[[ 0.17412685  0.59431808  0.40824829]
 [ 0.5086532  -0.10172622 -0.81649658]
 [ 0.84317955 -0.79777052  0.40824829]]


## **5. Conclusión**


NumPy es una biblioteca poderosa que facilita cálculos numéricos eficientes en Python. Comprender sus fundamentos es crucial para tareas de análisis de datos, computación científica y aprendizaje automático.