# JORDI BLASCO LOZANO

# 9.0 NetworkX
## 9.1, 9.2 Instalacion y Importaciones de paquetes

In [61]:
# importamos todas la librerias que vayamos a usar y leemos el data set

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

WPCdata = pd.read_csv('padelWorldCupDicc.csv')
# muestro el data set para tener mas claro las columnas de la tabla y trabajar mejor
WPCdata

equipoID           nombreEq nombreJug1 nombreJug2  sets_ganados  \
0         1  electroingenieros       Juan    Pedrito            11   
1         2    termonuecleares      Pedro     Adrian            11   
2         3           ElPAPITO      Pablo      Elena             7   
3         4           LosPibes      Elena     Blanca            12   
4         5         herculanos     Carlos        Ana             9   
5         6         Palilleros   Federico     Carlos            11   
6         7         MaurosTeam      Mauro       Alex             5   
7         8     ParricaElMejor      Parra     Teresa             7   
8         9          Ganadores    Gonzalo       Paco             8   
9        10          UltraTeam       Sara       Luis             7   

   sets_perdidos  partidos_ganados  partidos_perdidos         enfrentamientos  \
0              7                 4                  3  [2, 4, 3, 10, 5, 7, 6]   
1              7                 4                  3  [1, 8, 10, 7, 4, 6, 9]   
2             10                 3                  4  [4, 9, 1, 6, 7, 5, 10]   
3              5                 6                  1  [3, 1, 5, 8, 2, 10, 7]   
4             10                 3                  4  [6, 10, 4, 9, 1, 3, 8]   
5              7                 5                  2   [5, 7, 8, 3, 9, 2, 1]   
6             11                 2                  5   [8, 6, 9, 2, 3, 1, 4]   
7             11                 3                  4  [7, 2, 6, 4, 10, 9, 5]   
8              9                 3                  4  [10, 3, 7, 5, 6, 8, 2]   
9             11                 2                  5   [9, 5, 2, 1, 8, 4, 3]   

   puntos           puntos_por_jornada  dineroGenerado  \
0       8     [0, 2, 2, 4, 4, 4, 6, 8]             650   
1       8     [0, 0, 0, 2, 4, 4, 6, 8]             700   
2       6     [0, 0, 2, 2, 2, 4, 4, 6]             600   
3      12   [0, 2, 4, 6, 6, 8, 10, 12]            1200   
4       6     [0, 0, 2, 2, 2, 4, 6, 6]             600   
5      10  [0, 2, 4, 6, 8, 10, 10, 10]             950   
6       4     [0, 0, 0, 2, 2, 2, 2, 4]             500   
7       6     [0, 2, 4, 4, 6, 6, 6, 6]             600   
8       6     [0, 2, 2, 2, 4, 4, 6, 6]            1150   
9       4     [0, 0, 0, 0, 2, 4, 4, 4]             600   

   mediaEspectadoresPorEquipo  entradasVendidasPorEquipo         pais  
0                         550                        100       España  
1                         405                         80         EEUU  
2                         900                         90        China  
3                         830                         70          URS  
4                         450                        100        China  
5                         670                         80        Nepal  
6                         880                         90  R.D. Congo   
7                         550                        100       España  
8                         950                        120        China  
9                         800                         80      Nigeria

# 9.3 Creacion de un grafo
 creamos un grafo vacion con nx.Graph() 

In [62]:
G = nx.Graph() # grafo no dirigido
print(G)
G = nx.DiGraph() # grafo dirigido
print(G)

Graph with 0 nodes and 0 edges
DiGraph with 0 nodes and 0 edges


## 9.3.1 Creacion de un grafo desde una matriz numpy

In [63]:
G = nx.Graph(np.array([[0, 1, 1], [1, 0, 1], [0, 1, 0]])) # usamos una matriz de adyacencia para crear el grafo
print(G)
print(G.nodes) # mostramos los nodos del grafo
print(G.edges) # mostramos las conexiones
print(nx.adjacency_matrix(G).todense()) # mostramos la matriz de adyacencia

Graph with 3 nodes and 3 edges
[0, 1, 2]
[(0, 1), (0, 2), (1, 2)]
[[0 1 1]
 [1 0 1]
 [1 1 0]]


## 9.3.2 Creacion de un grafo desde un pandas DataFrame
Usaré una combinación de las dos maneras de crear un grafo de manera mas complicada, por lo que para la version facil de este apartado usare un pandas inventado y para la version complicada usare el data set de padelWoldCup 

In [64]:
df = pd.DataFrame({'from': [1, 2, 3, 4], 'to': [3, 3, 4, 2]}) # creamos un data frame con dos columnas from y to donde cada fila sera un nodo y con su conexion de la columna to
G = nx.from_pandas_edgelist(df, 'from', 'to')
print(G.nodes)
print(G.edges)

[1, 3, 2, 4]
[(1, 3), (3, 2), (3, 4), (2, 4)]


## 9.3.2.1 Creacion de un grafo desde un pandas DataFrame version compleja + 
### 9.3.3, 9.3.4 Añadir nodos y conexiones
Para este apartado voy a definir primero las dos variables que necesito, (seran de tipo np.array). Primero definire todos los nodos ('equipoID') y despues las conexiones ('enfrentamientos'). Creare un grafo vacio no dirigido y añadire los nodos, por ultimo con dos bucles anidados añadire las conexiones que representaran los enfrentamientos de cada equipo.

In [65]:

equipoID = np.array(WPCdata['equipoID']) # seleccionamos la columna equipoID y la convertimos en un array
enfrentamientos = np.array(WPCdata['enfrentamientos'].apply(eval).tolist()) # seleccionamos la columna enfrentamientos del PD y antes de convertirla en un array la convertimos en una lista quitandole las comillas y los corchetes con la funcion eval para que no usemos strings


G = nx.Graph() # creamos un grafo vacio no dirigido
G.add_nodes_from(equipoID) # con la funcion add_nodes_from añadimos los nodos al grafo, en este caso en forma de array, pero podria ser una lista normal, un unico nodo, etc


for equipo in equipoID: # usamos un bucle que recorra cada equipo en la lista de equipos
    for j in range(len(enfrentamientos[equipo-1])): # como tenemos las conexiones guardadas en una lista de la siguiente forma '[[1,2,3],[2,3,4]]' usamos un bucle que recorra cada enfrentamiento de cada equipo de forma que cada j será un enfrentamiento del equipo i contra el equipo j
        G.add_edge(equipo,enfrentamientos[equipo-1][j]) # añadimos las conexiones al grafo con la funcion add_edge que añadira una conexion entre el equipo i y el equipo j que se encuentre en la lista de enfrentamientos del equipo i

print(G.nodes) # mostraremos los nodos del grafo
print(G.edges) # y tambien las conexiones que concordaran con los enfrentamientos de cada equipo

   

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[(1, 2), (1, 4), (1, 3), (1, 10), (1, 5), (1, 7), (1, 6), (2, 8), (2, 10), (2, 7), (2, 4), (2, 6), (2, 9), (3, 4), (3, 9), (3, 6), (3, 7), (3, 5), (3, 10), (4, 5), (4, 8), (4, 10), (4, 7), (5, 6), (5, 10), (5, 9), (5, 8), (6, 7), (6, 8), (6, 9), (7, 8), (7, 9), (8, 10), (8, 9), (9, 10)]


## 9.3.3, 9.3.4 Atributos de los nodos y las conexiones

In [66]:
# atributos de los nodos

partidos_ganados = dict(zip(equipoID, WPCdata['partidos_ganados'])) # creamos un diccionario con los equipos como clave y el numero de partidos ganados como valor
nx.set_node_attributes(G, partidos_ganados, 'partidos_ganados') # añadimos un atributo a los nodos que sera el numero de partidos ganados

nombres = dict(zip(equipoID, WPCdata['nombreEq'])) # elegimos otro atributo para los nodos que sera el nombre del equipo
nx.set_node_attributes(G, nombres, 'nombreEq') # lo añadimos al grafo

for i in equipoID:
    print(equipoID[i-1], G.nodes[i]) # mostramos los nodos con sus atributos


1 {'partidos_ganados': 4, 'nombreEq': 'electroingenieros'}
2 {'partidos_ganados': 4, 'nombreEq': 'termonuecleares'}
3 {'partidos_ganados': 3, 'nombreEq': 'ElPAPITO'}
4 {'partidos_ganados': 6, 'nombreEq': 'LosPibes'}
5 {'partidos_ganados': 3, 'nombreEq': 'herculanos'}
6 {'partidos_ganados': 5, 'nombreEq': 'Palilleros'}
7 {'partidos_ganados': 2, 'nombreEq': 'MaurosTeam'}
8 {'partidos_ganados': 3, 'nombreEq': 'ParricaElMejor'}
9 {'partidos_ganados': 3, 'nombreEq': 'Ganadores'}
10 {'partidos_ganados': 2, 'nombreEq': 'UltraTeam'}


In [67]:
# atributos de las conexiones

# nos inventamos un atributo para cada partido como por ejemplo el numero de entradas vendidas de cada partido

entradas = dict(zip(G.edges, np.random.randint(200, 700, len(G.edges)))) # volvemos a usar un diccionario con las conexiones como clave y el numero de entradas vendidas como valor
nx.set_edge_attributes(G, entradas, 'entradas_vendidas_part') # añadimos un atributo a las conexiones que sera el numero de entradas vendidas

sets = dict(zip(G.edges, np.random.randint(2, 4, len(G.edges)))) # nos inventamos otro atributo para cada partido como por ejemplo el numero de sets jugados
nx.set_edge_attributes(G, sets, 'sets_jugados') # añadimos un atributo a las conexiones que sera el numero de sets jugados de cada partido

print(G.edges(data=True)) # y mostramos todos los partidos con sus entradas y sus sets judados


[(1, 2, {'entradas_vendidas_part': 631, 'sets_jugados': 3}), (1, 4, {'entradas_vendidas_part': 604, 'sets_jugados': 2}), (1, 3, {'entradas_vendidas_part': 385, 'sets_jugados': 2}), (1, 10, {'entradas_vendidas_part': 452, 'sets_jugados': 3}), (1, 5, {'entradas_vendidas_part': 595, 'sets_jugados': 2}), (1, 7, {'entradas_vendidas_part': 521, 'sets_jugados': 3}), (1, 6, {'entradas_vendidas_part': 205, 'sets_jugados': 2}), (2, 8, {'entradas_vendidas_part': 655, 'sets_jugados': 2}), (2, 10, {'entradas_vendidas_part': 367, 'sets_jugados': 3}), (2, 7, {'entradas_vendidas_part': 526, 'sets_jugados': 2}), (2, 4, {'entradas_vendidas_part': 508, 'sets_jugados': 3}), (2, 6, {'entradas_vendidas_part': 262, 'sets_jugados': 3}), (2, 9, {'entradas_vendidas_part': 292, 'sets_jugados': 3}), (3, 4, {'entradas_vendidas_part': 202, 'sets_jugados': 3}), (3, 9, {'entradas_vendidas_part': 441, 'sets_jugados': 2}), (3, 6, {'entradas_vendidas_part': 390, 'sets_jugados': 3}), (3, 7, {'entradas_vendidas_part': 598

## 9.3.5 Eliminacion de nodos y conexiones

In [68]:
T = G.copy() # copiamos el grafo G en T para asi poder eliminar nodos y conexiones sin perder el grafo original

T.remove_node(1) # eliminamos el nodo 1
T.remove_edge(3,4) # eliminamos la conexion entre el nodo 2 y el nodo 3
print(T) # mostramos el grafo T que sera el grafo G pero sin el nodo 1 y sus 7 conexiones y sin la conexion entre el nodo 3 y el nodo 4 por lo que tendra 9 nodos y 27 conexiones
print(T.nodes)
print(T.edges)

# tambien podemos eliminar varios nodos y conexiones a la vez
T.remove_nodes_from([2,3,4]) # eliminamos los nodos que pasemos en forma de lista
T.remove_edges_from([(7,8),(6,8),(8,10)]) # y eliminamos las conexiones que pasemos en forma de lista
print(T) 
print(T.nodes)
print(T.edges)

Graph with 9 nodes and 27 edges
[2, 3, 4, 5, 6, 7, 8, 9, 10]
[(2, 8), (2, 10), (2, 7), (2, 4), (2, 6), (2, 9), (3, 9), (3, 6), (3, 7), (3, 5), (3, 10), (4, 5), (4, 8), (4, 10), (4, 7), (5, 6), (5, 10), (5, 9), (5, 8), (6, 7), (6, 8), (6, 9), (7, 8), (7, 9), (8, 10), (8, 9), (9, 10)]
Graph with 6 nodes and 9 edges
[5, 6, 7, 8, 9, 10]
[(5, 6), (5, 10), (5, 9), (5, 8), (6, 7), (6, 9), (7, 9), (8, 9), (9, 10)]


## 9.3.6, 9.3.7 Acceso a los nodos, las conexiones y sus atributos

In [69]:
print(G.nodes) # muestra los nodos del grafo
print(G.edges) # muestra las conexiones del grafo

print(G.nodes[1]) # muestra los atributos del nodo 1
print(G.edges[(1,2)]) # muestra los atributos de la conexion entre el nodo 1 y el nodo 2

# si por ejemplo quisieramos saber que equipos han jugado contra el equipo electroingenieros podriamos hacer lo siguiente
print()
for i in G.nodes:
    if 'electroingenieros' == G.nodes[i]['nombreEq']:
        print(G.edges(i)) # mostrara el ID del equipo ('electroingenieros') y los ID de los equipos con los que ha jugado

# si ahora quisieramos saber la informacion de cada partido jugado por el equipo 1 podriamos hacer lo siguiente:
print()
for i in G.edges:
    if 1 in i:
        print(G.edges[i]) 


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[(1, 2), (1, 4), (1, 3), (1, 10), (1, 5), (1, 7), (1, 6), (2, 8), (2, 10), (2, 7), (2, 4), (2, 6), (2, 9), (3, 4), (3, 9), (3, 6), (3, 7), (3, 5), (3, 10), (4, 5), (4, 8), (4, 10), (4, 7), (5, 6), (5, 10), (5, 9), (5, 8), (6, 7), (6, 8), (6, 9), (7, 8), (7, 9), (8, 10), (8, 9), (9, 10)]
{'partidos_ganados': 4, 'nombreEq': 'electroingenieros'}
{'entradas_vendidas_part': 631, 'sets_jugados': 3}

[(1, 2), (1, 4), (1, 3), (1, 10), (1, 5), (1, 7), (1, 6)]

{'entradas_vendidas_part': 631, 'sets_jugados': 3}
{'entradas_vendidas_part': 604, 'sets_jugados': 2}
{'entradas_vendidas_part': 385, 'sets_jugados': 2}
{'entradas_vendidas_part': 452, 'sets_jugados': 3}
{'entradas_vendidas_part': 595, 'sets_jugados': 2}
{'entradas_vendidas_part': 521, 'sets_jugados': 3}
{'entradas_vendidas_part': 205, 'sets_jugados': 2}


## 9.3.8 Acceso a los vecinos de un nodo

In [70]:
# para saber los vecinos de un nodo usamos la funcion neighbors
# asi nos es mas facil saber contra que equipos ha jugado el equipo 1 ya que simplemente nos pasa una lista con los ID de los equipos con los que ha jugado

print(list(G.neighbors(1))) 


[2, 4, 3, 10, 5, 7, 6]


## 9.3.9 Acceso al grado de un nodo

In [71]:
# para saber el grado de un nodo usamos la funcion degree
# en este caso sabemos que el equipo 1 ha jugado 7 partidos por lo que su grado sera 7
print(G.degree(1))

7


## 9.3.10 Acceso al numero de nodos y conexiones

In [72]:
# ya vimos que con la funcion print('Grafo') nos mostraba el numero de nodos y conexiones
# si saber el numero de nodos o conexiones por separado y en forma de entero usamos la funcion number_of_nodes y number_of_edges
print(G)
print(G.number_of_nodes())
print(G.number_of_edges())

Graph with 10 nodes and 35 edges
10
35


## 9.3.11 Acceso la matriz de adyacencia de un grafo

In [73]:
# para acceder a la matriz de adyacencia de un grafo usamos la funcion adjacency_matrix
# sera una matriz cuadrada donde las filas y las columnas seran los nodos y los valores seran 1 si ha habido un partido jugado entre los dos equipos y 0 si no

print(nx.adjacency_matrix(G).todense())

[[0 1 1 1 1 1 1 0 0 1]
 [1 0 0 1 0 1 1 1 1 1]
 [1 0 0 1 1 1 1 0 1 1]
 [1 1 1 0 1 0 1 1 0 1]
 [1 0 1 1 0 1 0 1 1 1]
 [1 1 1 0 1 0 1 1 1 0]
 [1 1 1 1 0 1 0 1 1 0]
 [0 1 0 1 1 1 1 0 1 1]
 [0 1 1 0 1 1 1 1 0 1]
 [1 1 1 1 1 0 0 1 1 0]]


## 9.3.12 Acceso a la matriz de grado de un grafo

In [74]:
# para acceder a la matriz de grado de un grafo usamos la funcion degree_matrix
# sera una matriz donde en la diagonal apareceran la cantidad de partidos jugados por cada equipo y el resto de valores seran 0
print(nx.degree_matrix(G).todense())

AttributeError: module 'networkx' has no attribute 'degree_matrix'